trigger:
  - '*'

parameters:
  - name: "SUBSCRIPTION"
    displayName: "Azure subscription hosting the infrastructure built with terraform"
    type: string
    default: PROD-IO-SERVICE-CONN
    values:
      - PROD-IO-SERVICE-CONN
      - DEV-IO-SERVICE-CONN

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: install_and_run_terraform
    steps:
      # 1 Install terraform
      - task: AzureCLI@2
        displayName: Install terraform
        inputs:
          scriptType: "bash"
          scriptLocation: "inlineScript"
          failOnStandardError: false
          inlineScript: |
            TERRAFORM_VERSION="$(cat .terraform-version)"
            wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            mv terraform /usr/local/bin/
            terraform -v
            rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - task: AzureCLI@2
        displayName: Install terrgrunt
        inputs:
          scriptLocation: "inlineScript"
          failOnStandardError: false
          inlineScript: |
            TERRAGRUNT_VERSION="$(cat .terragrunt-version)"
            wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
            mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
            terragrunt -v
