# Automatically triggered on PR
# Only triggers on branches
pr:
  autoCancel: true
  branches:
    exclude:
     - '*'

trigger:
  branches:
    exclude:
      - master
  paths:
    include:
      - 'prod/*'

parameters:
  - name: 'SUBSCRIPTION'
    displayName: 'Azure subscription hosting the infrastructure built with terraform'
    type: string
    default: PROD-IO-SERVICE-CONN
    values:
      - PROD-IO-SERVICE-CONN
      - DEV-IO-SERVICE-CONN
  - name: 'KEYVAULT_NAME'
    displayName: 'The key vault instance we want to backup.'
    type: string
    default: io-p-kv-common
  - name: 'STORAGE_ACCOUNT_NAME'
    displayName: 'Storage account where to save.'
    type: string
    default: iopstbackups
  - name: 'CONTAINER_NAME'
    displayName: 'Name of the container inside the storage account'
    type: string
    default: kv-secrets

pool:
  vmImage: 'ubuntu-latest'


jobs:
  - job: backup_secrets
    steps:
      # 1. Run bash script based on az cli
      - task: AzureCLI@2
        env:
          GIT_BRANCH: $(Build.SourceBranchName)
        displayName: Run backup secrets
        inputs:
          azureSubscription: '${{ parameters.SUBSCRIPTION }}'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: '.devops/backup-secrets.sh'
          failOnStandardError: false
          arguments:
            ${{ parameters.SUBSCRIPTION }}
            ${{ parameters.KEYVAULT_NAME }}
            ${{ parameters.STORAGE_ACCOUNT_NAME }}
            ${{ parameters.CONTAINER_NAME }}
